"""
Validates SQL generated by the LLM before it ever touches the database.

This is the piece that separates a "cool demo" from something you could
plausibly ship: an LLM will occasionally hallucinate a column, wrap SQL in
markdown fences, or -- if a prompt injection sneaks in through a future
feature -- try something destructive. None of that should reach the DB.

Design choices, on purpose:
  - Allow-list, not block-list, for the statement type: only SELECT/WITH.
  - Reject multiple statements (blocks stacked-query injection).
  - Reject any DDL/DML keyword even inside a comment or string, to be safe.
  - Force a LIMIT so a bad query can't return/scan an unbounded result set.
  - The DB connection this SQL runs against is opened read-only regardless
    (see app/db.py) -- guardrails.py is defense in depth, not the only line.
"""

import re

FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "REPLACE",
    "ATTACH", "DETACH", "PRAGMA", "VACUUM", "TRIGGER", "TRANSACTION",
    "GRANT", "REVOKE",
]

DEFAULT_ROW_LIMIT = 50


class UnsafeSQLError(ValueError):
    pass


def strip_markdown_fence(raw_sql: str) -> str:
    """LLMs love wrapping SQL in ```sql ... ``` -- strip that off if present."""
    cleaned = raw_sql.strip()
    cleaned = re.sub(r"^```(?:sql)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()


def validate_and_prepare(raw_sql: str, row_limit: int = DEFAULT_ROW_LIMIT) -> str:
    """
    Returns a safe-to-execute SQL string, or raises UnsafeSQLError.
    """
    sql = strip_markdown_fence(raw_sql)

    # Reject multiple statements (allow exactly one trailing semicolon).
    body = sql[:-1] if sql.endswith(";") else sql
    if ";" in body:
        raise UnsafeSQLError("Multiple SQL statements are not allowed.")

    if not re.match(r"^\s*(SELECT|WITH)\b", sql, flags=re.IGNORECASE):
        raise UnsafeSQLError("Only SELECT (or WITH ... SELECT) queries are allowed.")

    upper_sql = sql.upper()
    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{keyword}\b", upper_sql):
            raise UnsafeSQLError(f"Query contains a forbidden keyword: {keyword}")

    if not re.search(r"\bLIMIT\s+\d+\b", upper_sql):
        sql = f"{sql.rstrip(';')}\nLIMIT {row_limit}"

    return sql
